/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BrasileirosNoExteriorRouteImport } from './routes/brasileiros-no-exterior'
import { Route as EscritorioRouteImport } from './routes/escritorio'
import { Route as AreasDeAtuacaoIndexRouteImport } from './routes/areas-de-atuacao.index'
import { Route as AreasDeAtuacaoSlugRouteImport } from './routes/areas-de-atuacao.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasileirosNoExteriorRoute = BrasileirosNoExteriorRouteImport.update({
  id: '/brasileiros-no-exterior',
  path: '/brasileiros-no-exterior',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorioRoute = EscritorioRouteImport.update({
  id: '/escritorio',
  path: '/escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoIndexRoute = AreasDeAtuacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AreasDeAtuacaoRoute,
} as any)
const AreasDeAtuacaoSlugRoute = AreasDeAtuacaoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AreasDeAtuacaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRouteWithChildren
  '/blog': typeof BlogRoute
  '/brasileiros-no-exterior': typeof BrasileirosNoExteriorRoute
  '/escritorio': typeof EscritorioRoute
  '/areas-de-atuacao/$slug': typeof AreasDeAtuacaoSlugRoute
  '/areas-de-atuacao/': typeof AreasDeAtuacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/brasileiros-no-exterior': typeof BrasileirosNoExteriorRoute
  '/escritorio': typeof EscritorioRoute
  '/areas-de-atuacao/$slug': typeof AreasDeAtuacaoSlugRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRouteWithChildren
  '/blog': typeof BlogRoute
  '/brasileiros-no-exterior': typeof BrasileirosNoExteriorRoute
  '/escritorio': typeof EscritorioRoute
  '/areas-de-atuacao/$slug': typeof AreasDeAtuacaoSlugRoute
  '/areas-de-atuacao/': typeof AreasDeAtuacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas-de-atuacao'
    | '/blog'
    | '/brasileiros-no-exterior'
    | '/escritorio'
    | '/areas-de-atuacao/$slug'
    | '/areas-de-atuacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/brasileiros-no-exterior'
    | '/escritorio'
    | '/areas-de-atuacao/$slug'
    | '/areas-de-atuacao'
  id:
    | '__root__'
    | '/'
    | '/areas-de-atuacao'
    | '/blog'
    | '/brasileiros-no-exterior'
    | '/escritorio'
    | '/areas-de-atuacao/$slug'
    | '/areas-de-atuacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRouteWithChildren
  BlogRoute: typeof BlogRoute
  BrasileirosNoExteriorRoute: typeof BrasileirosNoExteriorRoute
  EscritorioRoute: typeof EscritorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasileiros-no-exterior': {
      id: '/brasileiros-no-exterior'
      path: '/brasileiros-no-exterior'
      fullPath: '/brasileiros-no-exterior'
      preLoaderRoute: typeof BrasileirosNoExteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritorio': {
      id: '/escritorio'
      path: '/escritorio'
      fullPath: '/escritorio'
      preLoaderRoute: typeof EscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao/': {
      id: '/areas-de-atuacao/'
      path: '/'
      fullPath: '/areas-de-atuacao/'
      preLoaderRoute: typeof AreasDeAtuacaoIndexRouteImport
      parentRoute: typeof AreasDeAtuacaoRoute
    }
    '/areas-de-atuacao/$slug': {
      id: '/areas-de-atuacao/$slug'
      path: '/$slug'
      fullPath: '/areas-de-atuacao/$slug'
      preLoaderRoute: typeof AreasDeAtuacaoSlugRouteImport
      parentRoute: typeof AreasDeAtuacaoRoute
    }
  }
}

interface AreasDeAtuacaoRouteChildren {
  AreasDeAtuacaoSlugRoute: typeof AreasDeAtuacaoSlugRoute
  AreasDeAtuacaoIndexRoute: typeof AreasDeAtuacaoIndexRoute
}

const AreasDeAtuacaoRouteChildren: AreasDeAtuacaoRouteChildren = {
  AreasDeAtuacaoSlugRoute: AreasDeAtuacaoSlugRoute,
  AreasDeAtuacaoIndexRoute: AreasDeAtuacaoIndexRoute,
}

const AreasDeAtuacaoRouteWithChildren = AreasDeAtuacaoRoute._addFileChildren(
  AreasDeAtuacaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRouteWithChildren,
  BlogRoute: BlogRoute,
  BrasileirosNoExteriorRoute: BrasileirosNoExteriorRoute,
  EscritorioRoute: EscritorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
