/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/areas-de-atuacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas-de-atuacao'
  id: '__root__' | '/' | '/areas-de-atuacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
